[".config/omarchy/plugins/tmn73.calendar"]
type = "git-repo"
url = "https://github.com/tmn73/omarchy-calendar.git"
refreshPeriod = "168h"

[".config/omarchy/plugins/crmne.hyprmoncfg"]
type = "git-repo"
url = "https://github.com/crmne/omarchy-hyprmoncfg.git"
refreshPeriod = "168h"
