-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A86",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL P2422H 1DL6QP3",
  mode = "1920x1080@60.00",
  position = "0x-1080",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL P2422H 1DL6QP3" })
hl.workspace_rule({ workspace = "7", monitor = "desc:BOE 0x0A86", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:BOE 0x0A86" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE 0x0A86" })
hl.workspace_rule({ workspace = "10", monitor = "desc:BOE 0x0A86" })
hl.workspace_rule({ workspace = "11", monitor = "desc:BOE 0x0A86" })
