dictionaries = [
    "en_us",
    "nl_nl",
]
words = [
    "Hyprland",
    "Marijn's",
    "Omarchy's",
    "crs",
    "declaratively",
    "derijk",
    "geof",
    "geospatial",
    "hypergraph",
    "hypergraphs",
    "hyprmoncfg",
    "lazydocker",
    "looknfeel",
    "natively",
    "omarchy",
    "planify",
    "pulseaudio",
    "screenrecording",
    "sparql",
    "triplestore",
    "triplestores",
    "tudelft",
    "unasserted",
    "venv",
    "voxtype",
    "wkt",
]
flag_words = [
    "todo",
    "fixme",
]
