# install tpm if not installed
set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set-option -g status-position top
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides "xterm-256color:Tc"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind r
# bind r source-file ~/.tmux.conf
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Unbind the default navigation keys if they exist
unbind C-h
unbind C-j
unbind C-k
unbind C-l

# Bind new keys for window navigation
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Use the mouse
set -g mouse on

# Map leader m to zoom
unbind m
bind-key m resize-pane -Z

# list of plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-nvim 'session'

set -g @catppuccin_flavour mocha

run '~/.config/tmux/plugins/tpm/tpm'
