# Extra autostart processes
# exec-once = uwsm app -- my-service

# Auto-assign messaging apps to workspace 11
windowrule = match:class ^(chrome-web\.whatsapp\.com__-Default)$, workspace 11
windowrule = match:class ^(signal)$, workspace 11

exec-once = uwsm app -- signal-desktop
exec-once = omarchy-launch-webapp 'https://web.whatsapp.com/'

# Auto-assign email apps to workspace 10
windowrule = match:class org.mozilla.Thunderbird, workspace 10

windowrule = match:class ^(chrome-mail.google.com__-Default)$, workspace 10
windowrule = match:class ^(chrome-outlook.office.com__mail_mfderijk@tud365.mail.onmicrosoft.com_-Default)$, workspace 10

exec-once = uwsm app -- thunderbird
# exec-once = omarchy-launch-webapp "https://mail.google.com"
# exec-once = omarchy-launch-webapp 'https://outlook.office.com/mail/mfderijk@tud365.mail.onmicrosoft.com/'

# Auto-assign browser to workspace 1
windowrule = match:class ^(zen)$, workspace 2
exec-once = uwsm app -- zen-nvidia
