# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2

# laptop screen bottom middle
monitor=eDP-1, 1920x1080, 690x1080, 1

# A random monitor will be put above my laptop screen
monitor=,preferred,690x0,1

# Home monitors are top left and right
monitor=desc:AOC 2490W1 APGL89A004124, 1920x1080, 0x0, 1
monitor=desc:AOC 2490W1 APGL69A003315, 1920x1080, 1920x0, 1

# Keybindings to disable and re-enable home monitors
bind=SUPER_SHIFT, F1, exec, hyprctl keyword monitor "desc:AOC 2490W1 APGL89A004124, disable"
bind=SUPER_SHIFT, F2, exec, hyprctl keyword monitor "desc:AOC 2490W1 APGL89A004124, 1920x1080, 0x0, 1"
bind=SUPER_SHIFT, F3, exec, hyprctl keyword monitor "desc:AOC 2490W1 APGL69A003315, disable"
bind=SUPER_SHIFT, F4, exec, hyprctl keyword monitor "desc:AOC 2490W1 APGL69A003315, 1920x1080, 1920x0, 1"

# LAPTOP LID STUFF
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 690x1080, 1"


# workspaces
workspace = 1, monitor:eDP-1
workspace = 2, monitor:desc:AOC 2490W1 APGL89A004124
workspace = 3, monitor:desc:AOC 2490W1 APGL89A004124
workspace = 4, monitor:desc:AOC 2490W1 APGL89A004124
workspace = 5, monitor:desc:AOC 2490W1 APGL89A004124
workspace = 6, monitor:desc:AOC 2490W1 APGL89A004124
workspace = 7, monitor:desc:AOC 2490W1 APGL69A003315
workspace = 8, monitor:desc:AOC 2490W1 APGL69A003315
workspace = 9, monitor:desc:AOC 2490W1 APGL69A003315
workspace = 10, monitor:desc:AOC 2490W1 APGL69A003315
workspace = 11, monitor:desc:AOC 2490W1 APGL69A003315
