-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AOC 2490W1 APGL69A003315",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE 0x0A86",
  mode = "1920x1080@60.00",
  position = "0x1080",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AOC 2490W1 APGL69A003315", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AOC 2490W1 APGL69A003315" })
hl.workspace_rule({ workspace = "3", monitor = "desc:AOC 2490W1 APGL69A003315" })
hl.workspace_rule({ workspace = "4", monitor = "desc:AOC 2490W1 APGL69A003315" })
hl.workspace_rule({ workspace = "5", monitor = "desc:AOC 2490W1 APGL69A003315" })
hl.workspace_rule({ workspace = "6", monitor = "desc:AOC 2490W1 APGL69A003315" })
