---
- name: Setup development environment
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    actual_user: "{{ ansible_user_id }}"
    actual_home: "{{ ansible_env.HOME }}"
    has_display: "{{ ansible_env.DISPLAY is defined or ansible_env.WAYLAND_DISPLAY is defined }}"

  roles:
    # always
    - cli_tools
    # when on a local machine
    - role: rust
      when: has_display
    - role: zen_browser
      when: has_display
    - role: keyd
      when: has_display
    - role: chezmoi_setup
      when: has_display
