---
- name: Setup development environment
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - onepassword
    - cli_tools
    - zen_browser
    - chezmoi_setup
