[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrains Mono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font Mono", style = "Italic" }

[window]
decorations = "none"

[window.padding]
x = 4
y = 4

[terminal.shell]
program = "/bin/fish"

[font]
size = 15
